import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useSelector } from "react-redux";
import { GroupsList } from "../functions/groups";
import { useEffect, useState } from "react";
import Groupcart from "../components/groups/homecart";
export default function Home() {
  const { name } = useSelector((state) => state.global);

  const [groups, setGroups] = useState([]);

  useEffect(() => {
    GroupsList().then((data) => {
      setGroups(data);
    });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" pb-20">
        <div>
          {/* {groups?.length} */}

          {/* -----groups map---- */}

          <div className=" mt-12 mx-12">
            {groups.map((group) => {
              return (
                <div key={group?.text} className=" my-8">
                  <Groupcart group={group} />
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </div>
  );
}
